### ISSUE TITLE
resolve pip upgrade error after pip fixed it!

### ISSUE THREAD

**Issue by Escapingbug** [Escapingbug/ancypwn#1]
https://github.com/pypa/pip/issues/5599

**Comment by CCbird** [comment]
Fix the pip update:

RUN pip install -U pip
RUN echo 'from pip import __main__' > /usr/bin/pip
RUN echo 'if __name__ == '__main__':' >> /usr/bin/pip
RUN echo '  sys.exit(__main__._main())' >> /usr/bin/pip

**Comment by Escapingbug** [comment]
Can you give me a pull request on how to fix that exactly? Alghough im not sure this is permanent fix.. Or can you adjust the docker file to remove the update part and test it for me? I'm right now a little bit busy on this one, and my network is too slow to test..

**Comment by Escapingbug** [comment]
@CCbird
