### ISSUE TITLE
build with aliyun problem

### ISSUE THREAD

**Issue by hurae** [Escapingbug/ancypwn#13]
the master branch is always faild to build directly in aliyun but outside term branch can. I'm confused about this, why?

**Comment by Escapingbug** [comment]
What kind of error you get? Could you please provide me with more information? I don't have such a server to debug directly..

**Comment by hurae** [comment]
Acutuall I have no idea. I tried to use aliyun's free service to build my private repository to pull the container anywhere. But the master brance always fail. I have tried to build out of mainland or not, use cache or not, but always fail. But the older version like outseide-term branch works.

The flowing is build log of version 18.04, other versions' log is similar, no error information:
docker image building is started ...
[ fetch stage begin.]
fetch dockerfile and context
HEAD is now at 9910af8 fix: daemon is not detached, which causes unexpected behavior when terminal opens up the process is closed
[fetch successfully.]
==========================================
[docker version.]
Client:
Version: 17.06.1-ce
API version: 1.30
Go version: go1.8.3
Git commit: 874a737
Built: Thu Aug 17 22:53:49 2017
OS/Arch: linux/amd64

Server:
Version: 17.06.1-ce
API version: 1.30 (minimum version 1.12)
Go version: go1.8.3
Git commit: 874a737
Built: Thu Aug 17 23:01:50 2017
OS/Arch: linux/amd64
Experimental: false
==========================================
[docker build stage begin.]
Sending build context to Docker daemon 3.072kB
Step 1/10 : FROM ubuntu:18.04
18.04: Pulling from library/ubuntu
898c46f3b1a1: Pulling fs layer
63366dfa0a50: Pulling fs layer
041d4cd74a92: Pulling fs layer
6e1bee0f8701: Pulling fs layer
6e1bee0f8701: Waiting
63366dfa0a50: Verifying Checksum
63366dfa0a50: Download complete
041d4cd74a92: Verifying Checksum
041d4cd74a92: Download complete
6e1bee0f8701: Verifying Checksum
6e1bee0f8701: Download complete
898c46f3b1a1: Verifying Checksum
898c46f3b1a1: Download complete
898c46f3b1a1: Pull complete
63366dfa0a50: Pull complete
041d4cd74a92: Pull complete
6e1bee0f8701: Pull complete
Digest: sha256:017eef0b616011647b269b5c65826e2e2ebddbe5d1f8c1e56b3599fb14fabec8
Status: Downloaded newer image for ubuntu:18.04
 ---> 94e814e2efa8
Step 2/10 : MAINTAINER Anciety <anciety512@gmail.com>
 ---> Running in a2bd9aa0f63b
 ---> e5d405980968
Removing intermediate container a2bd9aa0f63b
Step 3/10 : RUN dpkg --add-architecture i386 && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qy git nasm python build-essential python-dev python-pip python-setuptools libc6-dbg libc6-dbg:i386 gcc-multilib gdb-multiarch gcc wget curl glibc-source cmake python-capstone socat netcat ruby lxterminal && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && cd ~ && tar -xvf /usr/src/glibc/glib*.tar.xz
 ---> Running in 91182f065262
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [5436 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [264 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [159 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/restricted i386 Packages [5385 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [3910 B]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [361 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [154 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages [4083 B]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted i386 Packages [13.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages [1328 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/multiverse i386 Packages [177 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages [11.3 MB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [725 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages [10.7 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [939 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [619 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [6968 B]
Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages [7146 B]
Get:28 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [952 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [942 B]
Get:30 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages [3647 B]
Get:31 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3659 B]
Get:32 http://archive.ubuntu.com/ubuntu bionic-backports/main i386 Packages [941 B]
Fetched 30.4 MB in 12s (2583 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
 adwaita-icon-theme at-spi2-core binutils binutils-common
 binutils-x86-64-linux-gnu ca-certificates cmake-data cpp cpp-7 dbus
 dconf-gsettings-backend dconf-service dirmngr dpkg-dev fakeroot file
 fontconfig fontconfig-config fonts-dejavu-core fonts-lato g++ g++-7 gcc-7
 gcc-7-base gcc-7-multilib gcc-8-base:i386 gdb gdbserver gir1.2-glib-2.0
 git-man glib-networking glib-networking-common glib-networking-services
 gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
 gpgconf gpgsm gsettings-desktop-schemas gtk-update-icon-cache

**Comment by Escapingbug** [comment]
Umm. This seems to be a hard problem to fix without any error information... No more logs apart from this? The apt part is fine, next should be `pip` installing, but I don't see anything here. The `pip`  installation shouldn't have any errors I think.

**Comment by Escapingbug** [comment]
The only difference between older version and master branch should be the `notiterm`, but the logs here tell that there's something wrong about `pip`.

**Comment by hurae** [comment]
there is nothing else provided by ali's contaioner service. You can try it youself. It's totally free right now.

maybe the pip's "import __main__" problem? i notice the default version pip of ubuntu didn't work. when i build my own version of ancypwn, i used get-pip.py to upgrade to the latest version.

**Comment by Escapingbug** [comment]
Ping, is this still a problem? I've built the images several times recently, they work like a charm.

**Comment by hurae** [comment]
well, i use your build on dockerhub these days. and i am still using the traditional way, the alias way of mine, as i used before. it's good enough for me right now, so i didn't try more things.
