### ISSUE TITLE
Error run ancypwn run 

### ISSUE THREAD

**Issue by Chensem** [Escapingbug/ancypwn#17]
![image](https://user-images.githubusercontent.com/27469499/65017220-c2334480-d958-11e9-8078-97ec87d337fb.png)
![image](https://user-images.githubusercontent.com/27469499/65017229-c95a5280-d958-11e9-94d3-099db8e2c490.png)
![image](https://user-images.githubusercontent.com/27469499/65017238-cd867000-d958-11e9-8383-84894a9708cf.png)
e.. no such docker ?

**Comment by Escapingbug** [comment]
It means your docker image is not properly tagged. I have updated README, you can see how you should download the images and tag them properly there. Hope that helps.
