### ISSUE TITLE
This maybe caused by not completely installed ancypwn. [SOLUTION]

### ISSUE THREAD

**Issue by danielsmith0612** [Escapingbug/ancypwn#2]
```
$ sudo ancypwn run .
sh: xhost: command not found
This maybe caused by not completely installed ancypwn.
Have you read https://github.com/Escapingbug/ancypwn?

Traceback (most recent call last):
  File "/usr/local/bin/ancypwn", line 11, in <module>
    load_entry_point('ancypwn==0.2.5', 'console_scripts', 'ancypwn')()
  File "/Users/danielsmith/Library/Python/2.7/lib/python/site-packages/ancypwn.py", line 272, in main
    parse_args()
  File "/Users/danielsmith/Library/Python/2.7/lib/python/site-packages/ancypwn.py", line 110, in parse_args
    args.func(args)
  File "/Users/danielsmith/Library/Python/2.7/lib/python/site-packages/ancypwn.py", line 234, in run_pwn
    raise e
KeyError: 'DISPLAY'
```

### If you can't run a ancypwn with this error, you can try this command
```
$ export DISPLAY=0
$ sudo ancypwn run .
sh: xhost: command not found
Warning: Unable to get terminal size, you need to specify terminal size manually or your command line may behave strangely

 ________      ________       ________       ___    ___  ________    ___       __       ________      
|\   __  \    |\   ___  \    |\   ____\     |\  \  /  /||\   __  \  |\  \     |\  \    |\   ___  \    
\ \  \|\  \   \ \  \\ \  \   \ \  \___|     \ \  \/  / /\ \  \|\  \ \ \  \    \ \  \   \ \  \\ \  \   
 \ \   __  \   \ \  \\ \  \   \ \  \         \ \    / /  \ \   ____\ \ \  \  __\ \  \   \ \  \\ \  \  
  \ \  \ \  \   \ \  \\ \  \   \ \  \____     \/  /  /    \ \  \___|  \ \  \|\__\_\  \   \ \  \\ \  \ 
   \ \__\ \__\   \ \__\\ \__\   \ \_______\ __/  / /       \ \__\      \ \____________\   \ \__\\ \__\
    \|__|\|__|    \|__| \|__|    \|_______||\___/ /         \|__|       \|____________|    \|__| \|__|
                                           \|___|/                                                    
        
root@linuxkit-025000000001:/pwn#
```

**Comment by Escapingbug** [comment]
Thanks for reporting. Sorry for late reply, I was on some CTFs these two days. I will fix this right away. I really should consider this situation ahead. :)

**Comment by Escapingbug** [comment]
Could you please provide me with more information about your running environment? I only considered Xorg actually, as I saw your missing "xhost", I think this might be some environment differences. I might add more support for other environment if it is possible.

**Comment by danielsmith0612** [comment]
| ENVIRONMENT                   | VALUE          |
| ----------------------------- | -------------- |
| OS                            | Mac OS X       |
| OS_Version                    | 10.14.2        |
| OS_Build_Version              | 18C54          |
| Terminal                      | xterm-256color |
| Terminal_Program              | Apple_Terminal |
| Terminal_Program_VersionShell | 421.1          |
| Shell                         | bash           |
| Docker_Version                | 18.09.0        |
| Docker_Build                  | 4d60db4        |

This is my environment.

If you need other my environment information, anytime contact me. :D

**Comment by Escapingbug** [comment]
Ok, macos is not supported yet. But I'm working on it. My teammate has already get it running and with the terminal support. I will do some updates shortly after I solved this unfinished CTF challenge..

**Comment by Escapingbug** [comment]
I have done some basic stuff on macos, but yet I have no device to debug. On readme I have written some macos instructions to setup terminal support, but as far as I know xquatz actually have a DISPLAY environment set to a socket file. I was wondering if this socket file is usable within docker.

I was wondering if you could help me on this, to try the xquatz, and mount the socket file inside the docker container. And inside the docker container, setup the DISPLAY environment to point to the path to that socket file (within docker), see if `lxterminal` work.

Apparently my teammates have abandoned me...

**Comment by WinMin** [comment]
...

**Comment by Escapingbug** [comment]
Nevermind, my team mate has been back.
