### ISSUE TITLE
[BUG]Can't get new terminal on macos

### ISSUE THREAD

**Issue by WinMin** [Escapingbug/ancypwn#9]
[BUG] Can't bounce new terminal on macos
```bash
objc[1895]: +[NSString initialize] may have been in progress in another thread when fork() was called.
```
and got python crash like this:

![](https://blog-1252049492.cos.ap-hongkong.myqcloud.com/blog-img/20190301162306.png)

[solved ] 
```bash
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

**Comment by Escapingbug** [comment]
on readme already. Thanks for reporting.

**Comment by hebtuerror404** [comment]
我遇到了新的问题，也是无法弹出新的Term。
![](http://img.lhyerror404.cn/error404/2019-12-15-031115.png)
新的终端窗口未弹出。
顺便一提，在安装ancypwn-terminal-iterm2之后，其依赖包osascript不会被安装，需要手动安装才可以顺利运行test_run()函数并弹出新的终端窗口。
我无法确定本地的守护进程是否已被启动，在docker容器测试使用socket链接是可以成功发送数据的。
